#通过fastlane将产物推送到crashlytics
default_platform(:android)

$env_key_mobile_root = 'GITHUB_WORKSPACE'
$env_current_branch = 'CURRENT_BRANCH'
$env_current_tag = 'CURRENT_TAG'
$build_type_preview = 'preview'
$build_type_release = 'production'


$filename_preview_apk_default = 'app-preview-release.apk'
$filename_release_apk_default = 'app-production-release.apk'

$path_dir_build = ENV[$env_key_mobile_root]
$current_branch = ENV[$env_current_branch]
$current_tag = ENV[$env_current_tag]
#./build/app/outputs/apk/preview/release/app-preview-release.apk

$CURRENT_BRANCH = ENV[$env_key_mobile_root]
def print_header header
    UI.message "~~~~~~~~~~~~~~~~~~~~~~"
    UI.message '📍 ' + header.to_s
    UI.message "~~~~~~~~~~~~~~~~~~~~~~"
end

def print_log(content)
    UI.message '📠 ' + content.to_s
end

# --- Lanes ---
platform :android do
  before_all do
    print_header '🏁 Before All'
    print_log '$current_branch'
    print_log '$current_tag'
    sh('pwd')
  end

  desc 'Build & upload to Appcenter Beta'
  lane :beta do
    build_number = number_of_commits()
    print_log build_number
    print_log "Build Commits #{build_number}"
    Dir.chdir "../.." do
      sh('flutter', 'pub', 'get')
      sh('flutter', 'clean')
      sh('pwd')
      sh('flutter', 'build', 'apk', "--verbose --no-tree-shake-icons --release --flavor preview -t lib/main.dart --dart-define=username=wuxingjuan@ones.ai --dart-define=password=juan1997 --dart-define=isdev=true --dart-define=projectServerUrl=https://devapi.myones.net/project/F8032 --dart-define=wikiServerUrl=https://dev.myones.net/wiki/F8032 --build-number=#{build_number}")
      sh('cp','$path_dir_build/build/app/outputs/flutter-apk/app-production-release.apk','$path_dir_build/ones-ai-mobile-$current_branch.apk')
    end
    log = changelog_from_git_commits(
      pretty: '- %s (%cn)',
      include_merges: false
    )
    appcenter_upload(
      release_notes:log,
      file:'$path_dir_build/ones-ai-mobile-$current_branch.apk',
      notify_testers:true,
      api_token:ENV['APPCENTER_API_TOKEN_ANDROID'],
      app_name:ENV['APPCENTER_APP_NAME_ANDROID']
    )
  end

  desc "Build & upload to  Release"
  lane :release do
    build_number = number_of_commits()
    print_log 'Build Commits $build_number'
    log = changelog_from_git_commits(
      pretty: '- %s (%cn)',
      include_merges: false
    )
  end
end